name = "dawn-thunder-d18f"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-05-11"

binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'expired'
